version: '3.5'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  pgadmin:
    image: fenglc/pgadmin4
    environment:
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD=postgres
    ports:
      - 5050:5050
